apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
  namespace: policy-system
  labels:
    kustomize.toolkit.fluxcd.io/name: app-a
    kustomize.toolkit.fluxcd.io/namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-1
  template:
    metadata:
      labels:
        app: deployment-1
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:latest
        command: ["sleep", "100d"]
        securityContext:
          privileged: false
