apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service-2
  labels:
    app: my-service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-service-2
  template:
    metadata:
      labels:
        app: my-service-2
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:latest
        command: ["sleep", "100d"]
        securityContext:
          allowPrivilegeEscalation: false